/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as NicolasXiiRouteImport } from './routes/nicolas-xii'
import { Route as ManifesteRouteImport } from './routes/manifeste'
import { Route as ConfrerieRouteImport } from './routes/confrerie'
import { Route as IndexRouteImport } from './routes/index'

const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const NicolasXiiRoute = NicolasXiiRouteImport.update({
  id: '/nicolas-xii',
  path: '/nicolas-xii',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifesteRoute = ManifesteRouteImport.update({
  id: '/manifeste',
  path: '/manifeste',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfrerieRoute = ConfrerieRouteImport.update({
  id: '/confrerie',
  path: '/confrerie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confrerie': typeof ConfrerieRoute
  '/manifeste': typeof ManifesteRoute
  '/nicolas-xii': typeof NicolasXiiRoute
  '/recettes': typeof RecettesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confrerie': typeof ConfrerieRoute
  '/manifeste': typeof ManifesteRoute
  '/nicolas-xii': typeof NicolasXiiRoute
  '/recettes': typeof RecettesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confrerie': typeof ConfrerieRoute
  '/manifeste': typeof ManifesteRoute
  '/nicolas-xii': typeof NicolasXiiRoute
  '/recettes': typeof RecettesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confrerie' | '/manifeste' | '/nicolas-xii' | '/recettes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confrerie' | '/manifeste' | '/nicolas-xii' | '/recettes'
  id:
    | '__root__'
    | '/'
    | '/confrerie'
    | '/manifeste'
    | '/nicolas-xii'
    | '/recettes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfrerieRoute: typeof ConfrerieRoute
  ManifesteRoute: typeof ManifesteRoute
  NicolasXiiRoute: typeof NicolasXiiRoute
  RecettesRoute: typeof RecettesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nicolas-xii': {
      id: '/nicolas-xii'
      path: '/nicolas-xii'
      fullPath: '/nicolas-xii'
      preLoaderRoute: typeof NicolasXiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifeste': {
      id: '/manifeste'
      path: '/manifeste'
      fullPath: '/manifeste'
      preLoaderRoute: typeof ManifesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confrerie': {
      id: '/confrerie'
      path: '/confrerie'
      fullPath: '/confrerie'
      preLoaderRoute: typeof ConfrerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfrerieRoute: ConfrerieRoute,
  ManifesteRoute: ManifesteRoute,
  NicolasXiiRoute: NicolasXiiRoute,
  RecettesRoute: RecettesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
